from __future__ import annotations

from adv_finance.services.finance_controls.demand_letter_service import demand_letter_register

def execute(filters=None):
    cols=["Customer:Link/Customer:160","Letter Type:Data:130","Generated Date:Date:130","Overdue Amount:Currency:140","Oldest Days:Int:110","Generated By:Link/User:150","Sent Date:Date:120","Status:Data:120","Collection Case:Link/Collection Case:170"]
    rows=demand_letter_register(filters or {})
    return cols,[[r.customer,r.letter_type,r.generated_date,r.overdue_amount,r.oldest_overdue_days,r.generated_by,r.sent_date,r.status,r.collection_case] for r in rows]
