from frappe import _


def get_data():
    return [
        {
            "label": _("Accounts Payable"),
            "icon": "octicon octicon-checklist",
            "items": [
                {
                    "type": "doctype",
                    "name": "Supplier Reconciliation",
                    "label": _("Supplier Reconciliation"),
                    "description": _("Upload and reconcile supplier statements against ERPNext ledger entries."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Supplier Statement Template",
                    "label": _("Supplier Statement Template"),
                    "description": _("Configure CSV and XLSX supplier statement column mappings."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Payment Proposal",
                    "label": _("Payment Proposal"),
                    "description": _("Select due supplier invoices for controlled payment approval."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Payment Run",
                    "label": _("Payment Run"),
                    "description": _("Group approved payment selections and create draft Payment Entries."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Payment Hold",
                    "label": _("Payment Holds"),
                    "description": _("Block supplier or invoice payments with an auditable reason."),
                    "onboard": 1,
                },
                {
                    "type": "page",
                    "name": "supplier-reconciliation-manual",
                    "label": _("Supplier Reconciliation Manual"),
                    "description": _("User guide and monthly reconciliation workflow."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "Supplier Reconciliation History",
                    "doctype": "Supplier Reconciliation",
                    "label": _("Supplier Reconciliation History"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Open Supplier Reconciliation Exceptions",
                    "doctype": "Supplier Reconciliation",
                    "label": _("Open Supplier Reconciliation Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Account Reconciliation"),
            "icon": "octicon octicon-check",
            "items": [
                {
                    "type": "doctype",
                    "name": "Account Reconciliation Period",
                    "label": _("Reconciliation Period"),
                    "description": _("Generate and monitor period-end account reconciliations."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Account Reconciliation",
                    "label": _("Account Reconciliation"),
                    "description": _("Reconcile GL balances to supporting schedules, subledgers, or evidence."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Account Reconciliation Template",
                    "label": _("Reconciliation Templates"),
                    "description": _("Define account reconciliation method, tolerance, evidence, and risk."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "Account Reconciliation Status",
                    "doctype": "Account Reconciliation",
                    "label": _("Account Reconciliation Status"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Open Reconciling Items",
                    "doctype": "Account Reconciliation",
                    "label": _("Open Reconciling Items"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Aged Reconciling Items",
                    "doctype": "Account Reconciliation",
                    "label": _("Aged Reconciling Items"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Reconciliation Exceptions",
                    "doctype": "Account Reconciliation",
                    "label": _("Reconciliation Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Accounts Receivable"),
            "icon": "octicon octicon-credit-card",
            "items": [
                {
                    "type": "report",
                    "name": "Collection Workbench",
                    "doctype": "Collection Case",
                    "label": _("Collection Workbench"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "doctype",
                    "name": "Collection Case",
                    "label": _("Collection Cases"),
                    "description": _("Prioritize and manage customer collection work."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Promise to Pay",
                    "label": _("Promise to Pay"),
                    "description": _("Record customer payment commitments and monitor fulfilment."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Customer Dispute",
                    "label": _("Customer Disputes"),
                    "description": _("Track customer invoice disputes without reducing accounting receivables."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Credit Review",
                    "label": _("Credit Reviews"),
                    "description": _("Review exposure, behaviour, limits, and credit recommendations."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Credit Hold",
                    "label": _("Credit Holds"),
                    "description": _("Control operational credit holds and releases."),
                    "onboard": 1,
                },
            ],
        },
        {
            "label": _("Treasury"),
            "icon": "octicon octicon-graph",
            "items": [
                {
                    "type": "report",
                    "name": "Treasury Dashboard",
                    "doctype": "Cash Forecast",
                    "label": _("Treasury Dashboard"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Daily Cash Position",
                    "doctype": "Treasury Account",
                    "label": _("Daily Cash Position"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "doctype",
                    "name": "Cash Forecast",
                    "label": _("Cash Forecasts"),
                    "description": _("Generate frozen 13-week treasury cash forecast snapshots."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "13-Week Cash Forecast",
                    "doctype": "Cash Forecast",
                    "label": _("13-Week Cash Forecast"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "doctype",
                    "name": "Cash Forecast Scenario",
                    "label": _("Forecast Scenarios"),
                    "description": _("Define Base, Optimistic, Conservative, and Stress forecast adjustments."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Treasury Forecast Item",
                    "label": _("Treasury Forecast Items"),
                    "description": _("Maintain manual and recurring planning cash flows."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Treasury Account",
                    "label": _("Treasury Accounts"),
                    "description": _("Map ERPNext cash and bank accounts into treasury reporting."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Treasury Settings",
                    "label": _("Treasury Settings"),
                    "description": _("Configure company-specific treasury forecast defaults."),
                    "onboard": 1,
                },
            ],
        },
        {
            "label": _("Planning & Budget"),
            "icon": "octicon octicon-project-roadmap",
            "items": [
                {"type": "doctype", "name": "Budget Plan", "label": _("Budget Plans"), "description": _("Prepare, approve, version, forecast, and reforecast budgets."), "onboard": 1},
                {"type": "report", "name": "Budget Forecast", "doctype": "Budget Plan", "label": _("Budget Forecasts"), "is_query_report": True, "onboard": 0},
                {"type": "doctype", "name": "Budget Reservation", "label": _("Budget Reservations"), "description": _("Reserve available budget before formal procurement."), "onboard": 1},
                {"type": "doctype", "name": "Manual Budget Commitment", "label": _("Manual Commitments"), "description": _("Track approved commitments outside ERP procurement."), "onboard": 1},
                {"type": "doctype", "name": "Budget Transfer", "label": _("Budget Transfers"), "description": _("Move authorized budget between accounts, cost centers, and projects."), "onboard": 1},
                {"type": "doctype", "name": "Budget Supplement", "label": _("Budget Supplements"), "description": _("Increase authorized budget without overwriting original budget."), "onboard": 1},
                {"type": "doctype", "name": "Budget Override Request", "label": _("Budget Overrides"), "description": _("Approve one-time transaction budget overrides."), "onboard": 1},
                {"type": "doctype", "name": "Budget Control Rule", "label": _("Budget Control Rules"), "description": _("Configure warning and blocking thresholds for commitment-aware controls."), "onboard": 1},
                {"type": "doctype", "name": "Budget Settings", "label": _("Budget Settings"), "description": _("Configure company-specific budgeting and commitment behavior."), "onboard": 1},
            ],
        },
        {
            "label": _("Intercompany"),
            "icon": "octicon octicon-organization",
            "items": [
                {"type": "report", "name": "Intercompany Dashboard", "doctype": "Intercompany Transaction", "label": _("Intercompany Dashboard"), "is_query_report": True, "onboard": 0},
                {"type": "doctype", "name": "Intercompany Partner", "label": _("Partners"), "description": _("Configure intercompany partners, due-to/due-from accounts, tolerances, and settlement accounts."), "onboard": 1},
                {"type": "doctype", "name": "Intercompany Transaction", "label": _("Transactions"), "description": _("Registry of intercompany invoices, journals, payments, and manual adjustments."), "onboard": 1},
                {"type": "doctype", "name": "Intercompany Match", "label": _("Matching"), "description": _("Match one-to-one, one-to-many, many-to-one, and many-to-many intercompany activity."), "onboard": 1},
                {"type": "doctype", "name": "Intercompany Settlement", "label": _("Settlements"), "description": _("Track expected, partial, over, under, and completed intercompany settlements."), "onboard": 1},
                {"type": "doctype", "name": "Intercompany Difference", "label": _("Differences"), "description": _("Classify and resolve missing invoices, amount differences, FX differences, and duplicates."), "onboard": 1},
                {"type": "doctype", "name": "Intercompany Elimination Candidate", "label": _("Elimination Candidates"), "description": _("Prepare matched intercompany balances for future consolidation eliminations."), "onboard": 1},
            ],
        },
        {
            "label": _("Monitoring"),
            "icon": "octicon octicon-device-desktop",
            "items": [
                {
                    "type": "report",
                    "name": "Payment Run Exceptions",
                    "doctype": "Payment Run",
                    "label": _("Payment Run Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Accruals"),
            "icon": "octicon octicon-calendar",
            "items": [
                {
                    "type": "report",
                    "name": "Accrual Register",
                    "doctype": "Accrual",
                    "label": _("Accrual Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "doctype",
                    "name": "Accrual",
                    "label": _("Accruals"),
                    "description": _("Create, approve, reverse, and match expense accruals."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "Accrual Exceptions",
                    "doctype": "Accrual",
                    "label": _("Accrual Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Accrual Ageing",
                    "doctype": "Accrual",
                    "label": _("Accrual Ageing"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Accrual Variance Analysis",
                    "doctype": "Accrual",
                    "label": _("Accrual Variance Analysis"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Financial Close"),
            "icon": "octicon octicon-check-circle",
            "items": [
                {
                    "type": "doctype",
                    "name": "Financial Close Period",
                    "label": _("Close Periods"),
                    "description": _("Coordinate period-end close tasks, readiness, review, and approval."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Financial Close Template",
                    "label": _("Close Templates"),
                    "description": _("Define reusable month-end close procedures and dependencies."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Financial Close Task",
                    "label": _("Close Tasks"),
                    "description": _("Assigned close tasks with evidence, dependencies, and readiness checks."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "My Financial Close Tasks",
                    "doctype": "Financial Close Task",
                    "label": _("My Close Tasks"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Financial Close Status",
                    "doctype": "Financial Close Period",
                    "label": _("Financial Close Status"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Reports"),
            "icon": "octicon octicon-file",
            "items": [
                {
                    "type": "report",
                    "name": "Payment Proposal Register",
                    "doctype": "Payment Proposal",
                    "label": _("Payment Proposal Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Payment Run Register",
                    "doctype": "Payment Run",
                    "label": _("Payment Run Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Payment Hold Register",
                    "doctype": "Payment Hold",
                    "label": _("Payment Hold Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
    ]
