from frappe import _


def get_data():
    return [
        {
            "label": _("Accounts Payable"),
            "icon": "octicon octicon-checklist",
            "items": [
                {
                    "type": "doctype",
                    "name": "Supplier Reconciliation",
                    "label": _("Supplier Reconciliation"),
                    "description": _("Upload and reconcile supplier statements against ERPNext ledger entries."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Supplier Statement Template",
                    "label": _("Supplier Statement Template"),
                    "description": _("Configure CSV and XLSX supplier statement column mappings."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Payment Proposal",
                    "label": _("Payment Proposal"),
                    "description": _("Select due supplier invoices for controlled payment approval."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Payment Run",
                    "label": _("Payment Run"),
                    "description": _("Group approved payment selections and create draft Payment Entries."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Payment Hold",
                    "label": _("Payment Holds"),
                    "description": _("Block supplier or invoice payments with an auditable reason."),
                    "onboard": 1,
                },
                {
                    "type": "page",
                    "name": "supplier-reconciliation-manual",
                    "label": _("Supplier Reconciliation Manual"),
                    "description": _("User guide and monthly reconciliation workflow."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "Supplier Reconciliation History",
                    "doctype": "Supplier Reconciliation",
                    "label": _("Supplier Reconciliation History"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Open Supplier Reconciliation Exceptions",
                    "doctype": "Supplier Reconciliation",
                    "label": _("Open Supplier Reconciliation Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Account Reconciliation"),
            "icon": "octicon octicon-check",
            "items": [
                {
                    "type": "doctype",
                    "name": "Account Reconciliation Period",
                    "label": _("Reconciliation Period"),
                    "description": _("Generate and monitor period-end account reconciliations."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Account Reconciliation",
                    "label": _("Account Reconciliation"),
                    "description": _("Reconcile GL balances to supporting schedules, subledgers, or evidence."),
                    "onboard": 1,
                },
                {
                    "type": "doctype",
                    "name": "Account Reconciliation Template",
                    "label": _("Reconciliation Templates"),
                    "description": _("Define account reconciliation method, tolerance, evidence, and risk."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "Account Reconciliation Status",
                    "doctype": "Account Reconciliation",
                    "label": _("Account Reconciliation Status"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Open Reconciling Items",
                    "doctype": "Account Reconciliation",
                    "label": _("Open Reconciling Items"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Aged Reconciling Items",
                    "doctype": "Account Reconciliation",
                    "label": _("Aged Reconciling Items"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Reconciliation Exceptions",
                    "doctype": "Account Reconciliation",
                    "label": _("Reconciliation Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Monitoring"),
            "icon": "octicon octicon-device-desktop",
            "items": [
                {
                    "type": "report",
                    "name": "Payment Run Exceptions",
                    "doctype": "Payment Run",
                    "label": _("Payment Run Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Accruals"),
            "icon": "octicon octicon-calendar",
            "items": [
                {
                    "type": "report",
                    "name": "Accrual Register",
                    "doctype": "Accrual",
                    "label": _("Accrual Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "doctype",
                    "name": "Accrual",
                    "label": _("Accruals"),
                    "description": _("Create, approve, reverse, and match expense accruals."),
                    "onboard": 1,
                },
                {
                    "type": "report",
                    "name": "Accrual Exceptions",
                    "doctype": "Accrual",
                    "label": _("Accrual Exceptions"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Accrual Ageing",
                    "doctype": "Accrual",
                    "label": _("Accrual Ageing"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Accrual Variance Analysis",
                    "doctype": "Accrual",
                    "label": _("Accrual Variance Analysis"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
        {
            "label": _("Reports"),
            "icon": "octicon octicon-file",
            "items": [
                {
                    "type": "report",
                    "name": "Payment Proposal Register",
                    "doctype": "Payment Proposal",
                    "label": _("Payment Proposal Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Payment Run Register",
                    "doctype": "Payment Run",
                    "label": _("Payment Run Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
                {
                    "type": "report",
                    "name": "Payment Hold Register",
                    "doctype": "Payment Hold",
                    "label": _("Payment Hold Register"),
                    "is_query_report": True,
                    "onboard": 0,
                },
            ],
        },
    ]
